# Site settings
title: "clevelink"
description: "Flutter deep link demo."
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
include:
  - .well-known
